const DEFAULT_COURSE={
  id:"future-tech-speaking",title:"Future Technology Speaking",description:"처음 보는 답변부터 덩어리·단어 조립과 부분 회상을 거쳐 실전 전체 회상까지 단계별로 학습",builtIn:true,
  items:[
    {id:"q1",cue:"What specific future technology...",question:"What specific future technology or innovation are you most interested in exploring, and why?",answer:"I am interested in AI because it can make our lives easier.",meaning:""},
    {id:"q2",cue:"How has a specific piece...",question:"How has a specific piece of modern technology significantly changed your daily routine or habits?",answer:"My smartphone changed my daily life because it makes many things easier.",meaning:""},
    {id:"q3",cue:"Do you think technological advancements...",question:"Do you think technological advancements make human connections stronger or more isolated?",answer:"I think technology makes human connections stronger because we can communicate more easily.",meaning:""},
    {id:"q4",cue:"In what ways do you think automation...",question:"In what ways do you think automation and AI will impact the future job market?",answer:"I think AI will replace some jobs, but it will also create new jobs.",meaning:""},
    {id:"q5",cue:"What is the most serious ethical...",question:"What is the most serious ethical concern regarding the rapid development of biotechnology or AI?",answer:"The biggest problem is that AI may use personal information without permission.",meaning:""},
    {id:"q6",cue:"How can society address the digital...",question:"How can society address the digital divide between generations or different economic classes?",answer:"Society should give free digital lessons and cheaper devices to everyone.",meaning:""},
    {id:"q7",cue:"How does this technological issue...",question:"How does this technological issue relate to your future academic major or dream career?",answer:"This issue relates to my future computer science major because I want to build useful technology.",meaning:""},
    {id:"q8",cue:"If you become a professional...",question:"If you become a professional in your field, what innovative solution would you like to introduce?",answer:"If I become a software engineer, I want to create safe AI tools for everyone.",meaning:""},
    {id:"q9",cue:"What interdisciplinary knowledge...",question:"What interdisciplinary knowledge do you think is necessary to tackle complex modern technology problems?",answer:"We need knowledge of technology, science, math, and communication to solve problems.",meaning:""},
    {id:"q10",cue:"Are you generally optimistic or pessimistic...",question:"Are you generally optimistic or pessimistic about living in a heavily tech-driven future society?",answer:"I am optimistic because technology can make our lives easier and better.",meaning:""},
    {id:"q11",cue:"What is your final message...",question:"What is your final message on how humans should coexist with advanced technology?",answer:"Humans should use advanced technology wisely and always keep people in control.",meaning:""}
  ]
};

const STORE={courses:"recallRushCoursesV2",activeCourse:"recallRushActiveCourseV2",settings:"recallRushSettingsV3",progress:"recallRushProgressV3",xp:"recallRushXp",activity:"recallRushActivity",sessions:"recallRushSessions"};
const TYPE_META={
  expose:{label:"STEP 1 · 익히기",instruction:"먼저 정답 문장을 눈에 익혀봐",stage:1,xp:2},
  choose:{label:"STEP 2 · 고르기",instruction:"질문에 맞는 정답 문장을 골라봐",stage:1,xp:4},
  chunkOrder:{label:"STEP 3 · 덩어리 조립",instruction:"2~3단어씩 묶인 덩어리를 순서대로 놓아봐",stage:2,xp:5},
  order:{label:"STEP 4 · 단어 조립",instruction:"이번에는 단어 하나씩 눌러 문장을 만들어봐",stage:2,xp:6},
  cloze:{label:"STEP 5 · 빈칸",instruction:"빠진 단어만 골라 문장을 완성해봐",stage:3,xp:7},
  typePart:{label:"STEP 6 · 부분 회상",instruction:"앞부분을 보고 나머지를 직접 입력해봐",stage:4,xp:9},
  recall:{label:"STEP 7 · 전체 회상",instruction:"이제 질문 힌트만 보고 정답 전체를 써봐",stage:5,xp:12}
};
const LESSON_META={
  discover:{color:"green",icon:"book",description:"정답을 먼저 보고 보기 중에서 고르며 질문과 문장을 연결함.",flow:["정답 보기","정답 고르기"]},
  chunks:{color:"blue",icon:"layers",description:"긴 문장을 2~3단어 덩어리로 나눠 먼저 큰 구조를 맞춰봄.",flow:["덩어리 조립"]},
  build:{color:"blue",icon:"blocks",description:"단어 카드를 하나씩 조립하고 빈칸을 채우며 문장 구조를 더 정확히 익힘.",flow:["단어 조립","빈칸 채우기"]},
  recall:{color:"purple",icon:"keyboard",description:"문장 앞부분의 도움을 점점 줄이고 마지막에는 질문만 보고 전체를 회상함.",flow:["부분 입력","전체 회상"]},
  checkpoint:{color:"gold",icon:"check",description:"지금까지 배운 문장을 여러 문제 유형으로 섞어서 확인함.",flow:["덩어리","단어","빈칸","부분 입력","회상"]},
  final:{color:"gold",icon:"star",description:"실전처럼 질문 힌트만 보고 정답을 처음부터 끝까지 직접 회상함.",flow:["전체 회상"]}
};

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],clone=v=>JSON.parse(JSON.stringify(v));
const safeJson=(v,f)=>{try{return v?JSON.parse(v):f}catch{return f}};
const escapeHtml=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const state={courses:[],activeCourseId:null,settings:{orderMode:"original",chunkSize:2,learningMode:"beginner"},progressByCourse:{},path:[],selectedLessonId:null,editingCourseId:null,editorItems:[],session:null,lastResult:null};

function uid(prefix="id"){return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`}
function localDateKey(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}
function normalizeCourse(course){return {...course,items:(course.items||[]).map(item=>({meaning:"",cue:"",question:"",answer:"",...item}))}}
function loadState(){const stored=safeJson(localStorage.getItem(STORE.courses),[]);state.courses=[clone(DEFAULT_COURSE),...stored.filter(c=>c&&c.id!==DEFAULT_COURSE.id).map(normalizeCourse)];state.activeCourseId=localStorage.getItem(STORE.activeCourse)||DEFAULT_COURSE.id;if(!state.courses.some(c=>c.id===state.activeCourseId))state.activeCourseId=DEFAULT_COURSE.id;state.settings={...state.settings,...safeJson(localStorage.getItem(STORE.settings),{})};state.settings.chunkSize=Math.max(2,Math.min(4,Number(state.settings.chunkSize)||2));state.settings.learningMode=state.settings.learningMode==="fast"?"fast":"beginner";state.progressByCourse=safeJson(localStorage.getItem(STORE.progress),{});ensureCourseProgress(activeCourse().id)}
function persistCourses(){localStorage.setItem(STORE.courses,JSON.stringify(state.courses.filter(c=>c.id!==DEFAULT_COURSE.id)))}
function persistProgress(){localStorage.setItem(STORE.progress,JSON.stringify(state.progressByCourse))}
function persistSettings(){localStorage.setItem(STORE.settings,JSON.stringify(state.settings))}
function activeCourse(){return state.courses.find(c=>c.id===state.activeCourseId)||state.courses[0]}
function ensureCourseProgress(id){if(!state.progressByCourse[id])state.progressByCourse[id]={completedLessons:[],weak:{},attempts:{},mastered:{},stage:{},daily:{}};const p=state.progressByCourse[id];p.completedLessons||=[];p.weak||={};p.attempts||={};p.mastered||={};p.stage||={};p.daily||={};return p}
function getCourseProgress(){return ensureCourseProgress(activeCourse().id)}
function getGlobalStats(){const totalXp=Number(localStorage.getItem(STORE.xp)||0),a=safeJson(localStorage.getItem(STORE.activity),{}),today=localDateKey(),yesterday=localDateKey(new Date(Date.now()-86400000));let streak=Number(a.streak||0);if(a.lastDate&&a.lastDate!==today&&a.lastDate!==yesterday)streak=0;return{totalXp,streak}}
function saveGlobalCompletion(xp){localStorage.setItem(STORE.xp,String(Number(localStorage.getItem(STORE.xp)||0)+xp));localStorage.setItem(STORE.sessions,String(Number(localStorage.getItem(STORE.sessions)||0)+1));const a=safeJson(localStorage.getItem(STORE.activity),{}),today=localDateKey(),yesterday=localDateKey(new Date(Date.now()-86400000));let streak=Number(a.streak||0);if(a.lastDate!==today)streak=a.lastDate===yesterday?streak+1:1;localStorage.setItem(STORE.activity,JSON.stringify({lastDate:today,streak}))}
function makeCue(question){const words=String(question||"").trim().split(/\s+/).filter(Boolean);return words.length?`${words.slice(0,Math.min(5,words.length)).join(" ")}${words.length>5?"...":""}`:""}
function wordsOf(text){return String(text||"").trim().split(/\s+/).filter(Boolean)}
function chunksOf(text){const words=wordsOf(text);if(words.length<=3)return words;const size=words.length>=11?3:2,chunks=[];for(let i=0;i<words.length;i+=size)chunks.push(words.slice(i,i+size).join(" "));return chunks}
function shuffle(items){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function normalize(text){return String(text).normalize("NFKC").toLocaleLowerCase().replace(/[’‘]/g,"'").replace(/[^\p{L}\p{N}'\s]/gu," ").replace(/\s+/g," ").trim()}
function levenshtein(a,b){const m=Array.from({length:a.length+1},(_,i)=>[i]);for(let j=0;j<=b.length;j++)m[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++){const c=a[i-1]===b[j-1]?0:1;m[i][j]=Math.min(m[i-1][j]+1,m[i][j-1]+1,m[i-1][j-1]+c)}return m[a.length][b.length]}
function similarity(a,b){const x=normalize(a),y=normalize(b);if(!x||!y)return 0;return 1-levenshtein(x,y)/Math.max(x.length,y.length)}
function weakScore(id){return Number(getCourseProgress().weak[id]||0)}
function orderItems(items,mode=state.settings.orderMode){const copy=[...items];if(mode==="random")return shuffle(copy);if(mode==="weak")return copy.sort((a,b)=>weakScore(b.id)-weakScore(a.id));return copy}
function pathSignature(ids){let h=2166136261;for(const ch of ids.join("|")){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(36)}

function buildPath(course=activeCourse()){const items=course.items||[],chunkSize=Math.max(2,Math.min(4,Number(state.settings.chunkSize)||2)),beginner=state.settings.learningMode!=="fast",lessons=[],learned=[];let lessonNumber=1,group=0;for(let start=0;start<items.length;start+=chunkSize){const chunk=items.slice(start,start+chunkSize),ids=chunk.map(i=>i.id),sig=pathSignature(ids);group++;
  if(beginner)lessons.push({id:`discover-${chunkSize}-${start}-${sig}`,kind:"discover",group,color:"green",icon:"book",overline:`LESSON ${lessonNumber++}`,title:`문장 ${start+1}–${start+chunk.length} · 익히기`,description:LESSON_META.discover.description,itemIds:ids});
  if(beginner)lessons.push({id:`chunks-${chunkSize}-${start}-${sig}`,kind:"chunks",group,color:"blue",icon:"layers",overline:`LESSON ${lessonNumber++}`,title:`문장 ${start+1}–${start+chunk.length} · 덩어리`,description:LESSON_META.chunks.description,itemIds:ids});
  lessons.push({id:`build-${chunkSize}-${start}-${sig}-${beginner?"b":"f"}`,kind:"build",group,color:"blue",icon:"blocks",overline:`LESSON ${lessonNumber++}`,title:`문장 ${start+1}–${start+chunk.length} · 조립`,description:LESSON_META.build.description,itemIds:ids});
  lessons.push({id:`recall-${chunkSize}-${start}-${sig}-${beginner?"b":"f"}`,kind:"recall",group,color:"purple",icon:"keyboard",overline:`LESSON ${lessonNumber++}`,title:`문장 ${start+1}–${start+chunk.length} · 회상`,description:LESSON_META.recall.description,itemIds:ids});
  learned.push(...ids);const hasMore=start+chunkSize<items.length;if(hasMore&&group%2===0)lessons.push({id:`checkpoint-${chunkSize}-${group}-${pathSignature(learned)}`,kind:"checkpoint",group:`checkpoint-${group}`,color:"gold",icon:"check",overline:"CHECKPOINT",title:`${learned.length}문장 중간 점검`,description:LESSON_META.checkpoint.description,itemIds:[...learned],maxItems:Math.min(6,learned.length)})}
  if(items.length)lessons.push({id:`final-${pathSignature(items.map(i=>i.id))}`,kind:"final",group:"final",color:"gold",icon:"star",overline:"FINAL TEST",title:`실전 랜덤 ${Math.min(5,items.length)}`,description:LESSON_META.final.description,itemIds:items.map(i=>i.id),maxItems:Math.min(5,items.length)});return lessons}
function lessonItems(lesson){const course=activeCourse();let items=lesson.itemIds.map(id=>course.items.find(i=>i.id===id)).filter(Boolean),mix=["checkpoint","final","practice"].includes(lesson.kind),mode=mix&&state.settings.orderMode==="original"?"random":state.settings.orderMode;items=orderItems(items,mode);return lesson.maxItems&&items.length>lesson.maxItems?items.slice(0,lesson.maxItems):items}
function validCompletedLessonIds(){const valid=new Set(state.path.map(l=>l.id));return getCourseProgress().completedLessons.filter(id=>valid.has(id))}
function completedSet(){return new Set(validCompletedLessonIds())}
function firstIncompleteIndex(){const done=completedSet(),i=state.path.findIndex(l=>!done.has(l.id));return i===-1?Math.max(0,state.path.length-1):i}
function isLessonUnlocked(i){if(i===0)return true;const done=completedSet();return done.has(state.path[i-1].id)||done.has(state.path[i].id)}

function renderHome(){const course=activeCourse();ensureCourseProgress(course.id);state.path=buildPath(course);$("#courseTitle").textContent=course.title;$("#courseDescription").textContent=course.description||`${course.items.length}개 문장을 쉬운 문제부터 단계별로 학습`;$("#courseLabel").textContent=course.builtIn?"STARTER COURSE":"MY COURSE";$("#mobileCourseTitle").textContent=course.title;$("#mobileCourseInitial").textContent=(course.title.trim()[0]||"R").toUpperCase();$("#courseSentenceCount").textContent=course.items.length;renderPath();renderStats()}
function iconForLesson(lesson,unlocked){if(!unlocked)return"i-lock";return({book:"i-book",layers:"i-layers",blocks:"i-blocks",keyboard:"i-keyboard",check:"i-check",star:"i-star"}[lesson.icon]||"i-star")}
function renderPath(){const stage=$("#pathStage");stage.innerHTML="";if(!state.path.length){stage.innerHTML=`<div class="empty-path"><strong>아직 문장이 없음</strong><p>문장 세트에 화면에 보여줄 질문과 최종 정답을 넣으면 익히기부터 전체 회상까지 학습 경로가 자동으로 만들어짐.</p><button class="primary-button" id="emptyAddCourse" type="button">문장 세트 편집</button></div>`;$("#emptyAddCourse").addEventListener("click",()=>openCourseEditor(activeCourse().id));return}const done=completedSet(),current=firstIncompleteIndex();let lastGroup=null;state.path.forEach((lesson,index)=>{if(lesson.group!==lastGroup&&typeof lesson.group==="number"){const d=document.createElement("div");d.className="chapter-divider";d.textContent=`문장 묶음 ${lesson.group}`;stage.appendChild(d);lastGroup=lesson.group}if(lesson.kind==="checkpoint"||lesson.kind==="final"){const d=document.createElement("div");d.className="checkpoint-divider";d.textContent=lesson.kind==="final"?"실전 점검":"누적 복습";stage.appendChild(d);lastGroup=lesson.group}if(index===Math.ceil(state.path.length/2)){const m=document.createElement("div");m.className="path-mascot-row";m.innerHTML=`<img src="assets/mori.svg" alt="모리" class="path-mascot"><div class="mascot-note">정답 보기 → 고르기 → 덩어리 조립 → 단어 조립 → 빈칸 → 부분 입력 → 전체 회상 순으로 도움을 줄여감.</div>`;stage.appendChild(m)}const unlocked=isLessonUnlocked(index),completed=done.has(lesson.id),row=document.createElement("div");row.className=`path-row pos-${index%4}`;row.innerHTML=`<button class="lesson-node ${lesson.color!=="green"?lesson.color:""} ${completed?"completed":""} ${index===current&&unlocked?"current":""} ${unlocked?"":"locked"}" data-lesson-id="${lesson.id}" type="button" ${unlocked?"":"disabled"}><span class="node-shadow"></span><span class="node-face"><svg><use href="#${iconForLesson(lesson,unlocked)}"/></svg></span></button><div class="node-caption"><strong>${escapeHtml(lesson.title)}</strong><span>${completed?"완료 · 다시 연습 가능":unlocked?LESSON_META[lesson.kind].flow.join(" → "):"이전 단계 완료 후 열림"}</span></div>`;stage.appendChild(row)});$$(".lesson-node[data-lesson-id]").forEach(b=>b.addEventListener("click",()=>openLessonSheet(b.dataset.lessonId)))}
function renderStats(){const{totalXp,streak}=getGlobalStats();$("#totalXpMobile").textContent=totalXp;$("#streakDaysMobile").textContent=streak;const p=getCourseProgress(),completed=validCompletedLessonIds().length,total=state.path.length,percent=total?Math.min(100,Math.round(completed/total*100)):0;$("#completedLessonCount").textContent=completed;$("#weakCount").textContent=Object.values(p.weak).filter(v=>Number(v)>0).length;$("#masteryRingText").textContent=`${percent}%`;$(".mastery-ring").style.setProperty("--progress",`${percent*3.6}deg`);$("#masteryLabel").textContent=percent===100?"코스 완료":percent>=50?"절반 이상":percent>0?"진행 중":"시작 전";const today=localDateKey(),daily=Number(p.daily[today]||0);$("#dailyGoalCount").textContent=`${Math.min(2,daily)}/2`;$("#dailyGoalBar").style.width=`${Math.min(100,daily/2*100)}%`;$("#dailyGoalCopy").textContent=daily>=2?"오늘 목표 완료. 원하는 문제 유형으로 더 복습해도 됨.":`레슨 ${2-daily}개만 더 끝내면 오늘 목표 완료.`}
function openDialog(d){if(d&&typeof d.showModal==="function"&&!d.open)d.showModal()}
function closeDialog(d){if(d?.open)d.close()}
function flowForLesson(lesson){if(lesson.kind==="practice")return lesson.practiceType==="order"?["단어 조립"]:lesson.practiceType==="cloze"?["빈칸 채우기"]:lesson.practiceType==="recall"?["전체 회상"]:["약점 맞춤"];return LESSON_META[lesson.kind]?.flow||[]}
function openLessonSheet(id){const lesson=state.path.find(x=>x.id===id);if(!lesson)return;state.selectedLessonId=id;const items=lessonItems(lesson);$("#lessonSheetOverline").textContent=lesson.overline;$("#lessonSheetTitle").textContent=lesson.title;$("#lessonSheetDescription").textContent=lesson.description;$("#lessonSheetCount").textContent=`${items.length}문장`;$("#lessonSheetXp").textContent=`${generateExercises(lesson,items).length}문제`;$("#lessonSheetFlow").innerHTML=flowForLesson(lesson).map(x=>`<span>${escapeHtml(x)}</span>`).join("");const icon=$("#lessonSheetIcon");icon.className=`lesson-sheet-icon ${lesson.color==="green"?"":lesson.color}`;icon.innerHTML=`<svg><use href="#${iconForLesson(lesson,true)}"/></svg>`;openDialog($("#lessonSheet"))}
function startSelectedLesson(){const l=state.path.find(x=>x.id===state.selectedLessonId);if(!l)return;closeDialog($("#lessonSheet"));startLesson(l,lessonItems(l))}
function switchScreen(target){[$("#homeScreen"),$("#lessonScreen"),$("#resultScreen")].forEach(s=>s.classList.toggle("is-hidden",s!==target));window.scrollTo({top:0,behavior:"instant"})}

function makeExercise(type,item,depth=0){return{id:uid("ex"),type,itemId:item.id,item,depth}}
function adaptiveType(item){const stage=Number(getCourseProgress().stage[item.id]||0),weak=Number(getCourseProgress().weak[item.id]||0);if(stage<=1)return weak>2?"chunkOrder":"order";if(stage===2)return"cloze";if(stage===3)return"typePart";return weak>=3?"typePart":"recall"}
function generateExercises(lesson,items){const ex=[];if(lesson.kind==="discover")items.forEach(i=>ex.push(makeExercise("expose",i),makeExercise("choose",i)));else if(lesson.kind==="chunks")items.forEach(i=>ex.push(makeExercise("chunkOrder",i)));else if(lesson.kind==="build")items.forEach(i=>ex.push(makeExercise("order",i),makeExercise("cloze",i)));else if(lesson.kind==="recall")items.forEach(i=>ex.push(makeExercise("typePart",i),makeExercise("recall",i)));else if(lesson.kind==="checkpoint"){const types=["chunkOrder","order","cloze","typePart","recall"];items.forEach((i,n)=>ex.push(makeExercise(types[n%types.length],i)))}else if(lesson.kind==="final")items.forEach(i=>ex.push(makeExercise("recall",i)));else if(lesson.kind==="practice")items.forEach(i=>ex.push(makeExercise(lesson.practiceType==="weak"?adaptiveType(i):lesson.practiceType,i)));return ex}
function startLesson(lesson,items){if(!items.length)return;const exercises=generateExercises(lesson,items);state.session={lesson,lessonItems:items,queue:exercises,position:0,current:null,initialGradedCount:exercises.filter(e=>e.type!=="expose").length,firstTryCorrect:0,sessionXp:0,lives:5,feedbackOpen:false,currentHadHelp:false,missedIds:new Set(),remediationKeys:new Set(),ui:{}};switchScreen($("#lessonScreen"));$("#lessonKindLabel").textContent=lesson.overline||"PRACTICE";$("#lessonTitle").textContent=lesson.title;renderExercise()}
function renderExercise(){const s=state.session;if(!s||s.position>=s.queue.length)return finishLesson();const e=s.queue[s.position];s.current=e;s.feedbackOpen=false;s.currentHadHelp=false;s.ui={};$("#feedback").classList.add("is-hidden");$("#lessonFooter").classList.remove("correct","incorrect");$("#hintBox").classList.add("is-hidden");$("#hintBox").textContent="";$("#fullQuestion").classList.add("is-hidden");$("#fullQuestionToggle").textContent="전체 질문 보기";$("#questionCue").textContent=e.item.cue||makeCue(e.item.question);$("#fullQuestion").textContent=e.item.question;$("#exerciseTypeLabel").textContent=TYPE_META[e.type].label;$("#exerciseInstruction").textContent=TYPE_META[e.type].instruction;$("#questionCounter").textContent=`${Math.min(s.position+1,s.queue.length)} / ${s.queue.length}${e.depth?" · 다시":""}`;$("#lessonLives").textContent=s.lives;$("#progressBar").style.width=`${s.queue.length?s.position/s.queue.length*100:0}%`;$("#exerciseHelpers").classList.toggle("is-hidden",e.type==="expose");$("#hintButton").disabled=false;$("#revealButton").disabled=false;$("#checkButton").textContent=e.type==="expose"?"알겠어":"확인";$("#checkButton").disabled=e.type!=="expose";renderExerciseBody(e)}
function renderExerciseBody(e){const body=$("#exerciseBody");body.innerHTML="";if(e.type==="expose")return renderExpose(e,body);if(e.type==="choose")return renderChoose(e,body);if(e.type==="chunkOrder")return setupSequence(e,body,chunksOf(e.item.answer),"chunk");if(e.type==="order")return setupSequence(e,body,wordsOf(e.item.answer),"word");if(e.type==="cloze")return setupCloze(e,body);if(e.type==="typePart")return renderTypePart(e,body);return renderRecall(e,body)}
function renderExpose(e,body){const words=wordsOf(e.item.answer);body.innerHTML=`<div class="study-card"><span class="target-label">TARGET SENTENCE</span><div class="study-sentence">${escapeHtml(e.item.answer)}</div>${e.item.meaning?`<div class="study-meaning">${escapeHtml(e.item.meaning)}</div>`:""}<div class="study-chunks">${words.map(w=>`<span>${escapeHtml(w)}</span>`).join("")}</div></div>`}
function chooseOptions(item){const local=(state.session?.lessonItems||[]).filter(x=>x.id!==item.id).map(x=>x.answer),options=[item.answer,...shuffle(local).slice(0,2)];if(options.length<2){const words=wordsOf(item.answer);if(words.length>3){const swapped=[...words],i=Math.max(1,Math.floor(words.length/2)-1);[swapped[i],swapped[i+1]]=[swapped[i+1],swapped[i]];options.push(swapped.join(" "))}else options.push(`${item.answer} ...`)}return shuffle([...new Set(options)]).slice(0,3)}
function renderChoose(e,body){state.session.ui.options=chooseOptions(e.item);state.session.ui.selected=null;const draw=()=>{body.innerHTML=`<div class="option-list">${state.session.ui.options.map((o,i)=>`<button class="lesson-option ${state.session.ui.selected===i?"is-selected":""}" data-option-index="${i}" type="button"><span class="option-key">${String.fromCharCode(65+i)}</span><span>${escapeHtml(o)}</span></button>`).join("")}</div>`;body.querySelectorAll(".lesson-option").forEach(b=>b.addEventListener("click",()=>{state.session.ui.selected=Number(b.dataset.optionIndex);$("#checkButton").disabled=false;draw()}))};draw()}
function tokenBank(parts,prefix){return parts.map((text,index)=>({id:`${prefix}-${index}-${uid("t")}`,index,text}))}
function setupSequence(e,body,parts,prefix){const target=tokenBank(parts,prefix);state.session.ui.targetTokens=target;state.session.ui.bank=shuffle(target.map(t=>({...t})));state.session.ui.selected=[];renderSequenceBoard(body)}
function renderSequenceBoard(body=$("#exerciseBody")){const ui=state.session.ui,selected=ui.selected.map(id=>ui.bank.find(t=>t.id===id)).filter(Boolean);body.innerHTML=`<div class="build-board"><div class="answer-slot ${selected.length?"":"is-empty"}">${selected.map(t=>`<button class="selected-chip" data-token-id="${t.id}" type="button">${escapeHtml(t.text)}</button>`).join("")}</div><div class="word-bank">${ui.bank.map(t=>`<button class="word-chip ${ui.selected.includes(t.id)?"is-used":""}" data-token-id="${t.id}" type="button">${escapeHtml(t.text)}</button>`).join("")}</div></div>`;body.querySelectorAll(".word-chip").forEach(b=>b.addEventListener("click",()=>{if(!ui.selected.includes(b.dataset.tokenId))ui.selected.push(b.dataset.tokenId);$("#checkButton").disabled=ui.selected.length!==ui.targetTokens.length;renderSequenceBoard(body)}));body.querySelectorAll(".selected-chip").forEach(b=>b.addEventListener("click",()=>{ui.selected=ui.selected.filter(id=>id!==b.dataset.tokenId);$("#checkButton").disabled=true;renderSequenceBoard(body)}))}
function hiddenIndicesFor(words){const count=words.length<=3?1:Math.min(4,Math.max(2,Math.ceil(words.length*.3))),all=[...words.keys()],preferred=all.filter(i=>i>0||words.length<=3);return shuffle(preferred.length>=count?preferred:all).slice(0,count).sort((a,b)=>a-b)}
function setupCloze(e,body){const words=wordsOf(e.item.answer),hidden=hiddenIndicesFor(words),bank=shuffle(hidden.map(i=>({id:`cloze-${i}-${uid("t")}`,index:i,text:words[i]})));state.session.ui={words,hiddenIndices:hidden,bank,selected:[]};renderClozeBoard(body)}
function renderClozeBoard(body=$("#exerciseBody")){const ui=state.session.ui,selected=ui.selected.map(id=>ui.bank.find(t=>t.id===id)).filter(Boolean),map=new Map(ui.hiddenIndices.map((wordIndex,slot)=>[wordIndex,selected[slot]||null]));body.innerHTML=`<div class="build-board"><div class="cloze-line">${ui.words.map((w,i)=>map.has(i)?`<button class="cloze-blank ${map.get(i)?"filled":""}" data-blank-index="${i}" type="button">${map.get(i)?escapeHtml(map.get(i).text):"_____"}</button>`:`<span class="cloze-word">${escapeHtml(w)}</span>`).join("")}</div><div class="word-bank">${ui.bank.map(t=>`<button class="word-chip ${ui.selected.includes(t.id)?"is-used":""}" data-token-id="${t.id}" type="button">${escapeHtml(t.text)}</button>`).join("")}</div></div>`;body.querySelectorAll(".word-chip").forEach(b=>b.addEventListener("click",()=>{if(ui.selected.length<ui.hiddenIndices.length&&!ui.selected.includes(b.dataset.tokenId))ui.selected.push(b.dataset.tokenId);$("#checkButton").disabled=ui.selected.length!==ui.hiddenIndices.length;renderClozeBoard(body)}));body.querySelectorAll(".cloze-blank.filled").forEach(b=>b.addEventListener("click",()=>{const slot=ui.hiddenIndices.indexOf(Number(b.dataset.blankIndex));if(slot>=0)ui.selected.splice(slot,1);$("#checkButton").disabled=true;renderClozeBoard(body)}))}
function renderTypePart(e,body){const words=wordsOf(e.item.answer);if(words.length<2){state.session.ui.prefix="";state.session.ui.expected=e.item.answer;body.innerHTML=`<textarea id="dynamicInput" class="typing-input" rows="4" placeholder="문장을 입력"></textarea>`}else{const split=Math.max(1,Math.min(words.length-1,Math.floor(words.length*.45)));state.session.ui.prefix=words.slice(0,split).join(" ");state.session.ui.expected=words.slice(split).join(" ");body.innerHTML=`<div class="partial-wrap"><div class="partial-prefix">${escapeHtml(state.session.ui.prefix)} <span>…</span></div><textarea id="dynamicInput" class="typing-input" rows="4" placeholder="나머지 문장만 입력"></textarea></div>`}const input=$("#dynamicInput");input.addEventListener("input",()=>{$("#checkButton").disabled=!input.value.trim()});setTimeout(()=>input.focus({preventScroll:true}),50)}
function renderRecall(e,body){state.session.ui.expected=e.item.answer;body.innerHTML=`<textarea id="dynamicInput" class="typing-input" rows="5" placeholder="정답 문장 전체를 입력"></textarea>`;const input=$("#dynamicInput");input.addEventListener("input",()=>{$("#checkButton").disabled=!input.value.trim()});setTimeout(()=>input.focus({preventScroll:true}),50)}
function responseForCurrent(){const e=state.session.current,ui=state.session.ui;if(e.type==="expose")return e.item.answer;if(e.type==="choose")return ui.options?.[ui.selected]||"";if(e.type==="chunkOrder"||e.type==="order")return ui.selected.map(id=>ui.bank.find(t=>t.id===id)?.text||"").join(" ");if(e.type==="cloze"){const result=[...ui.words];ui.hiddenIndices.forEach((wordIndex,slot)=>{const t=ui.bank.find(x=>x.id===ui.selected[slot]);if(t)result[wordIndex]=t.text});return result.join(" ")}const typed=$("#dynamicInput")?.value.trim()||"";return e.type==="typePart"?`${ui.prefix||""} ${typed}`.trim():typed}
function markExposure(id){const p=getCourseProgress();p.stage[id]=Math.max(1,Number(p.stage[id]||0));persistProgress()}
function trackAttempt(id,correct,type){const p=getCourseProgress(),stage=TYPE_META[type]?.stage||1;p.attempts[id]=Number(p.attempts[id]||0)+1;if(correct){p.stage[id]=Math.max(stage,Number(p.stage[id]||0));p.mastered[id]=Number(p.mastered[id]||0)+(stage>=4?1:0);p.weak[id]=Math.max(0,Number(p.weak[id]||0)-(stage>=4?2:1))}else p.weak[id]=Number(p.weak[id]||0)+(stage>=4?2:1);persistProgress()}
function checkCurrentExercise(){const s=state.session;if(!s)return;if(s.feedbackOpen)return nextExercise();const e=s.current;if(e.type==="expose"){markExposure(e.itemId);s.sessionXp+=TYPE_META.expose.xp;s.feedbackOpen=true;showFeedback("correct","좋아, 이제 가볍게 확인해보자",`+${TYPE_META.expose.xp} XP · 다음 문제에서는 정답을 직접 고르게 됨.`);lockCurrent("계속");return}const response=responseForCurrent();if(!response)return;const target=e.item.answer,score=similarity(response,target),strict=["choose","chunkOrder","order","cloze"].includes(e.type),correct=strict?normalize(response)===normalize(target):score>=.93;correct?handleCorrect(score):handleIncorrect(score)}
function handleCorrect(score){const s=state.session,e=s.current;s.feedbackOpen=true;if(e.depth===0&&!s.currentHadHelp)s.firstTryCorrect++;const base=TYPE_META[e.type].xp,earned=s.currentHadHelp?Math.max(1,Math.floor(base/2)):base;s.sessionXp+=earned;trackAttempt(e.itemId,true,e.type);const near=score<.985&&["typePart","recall"].includes(e.type);showFeedback("correct",near?"거의 정확해!":e.type==="recall"?"완전히 떠올렸어!":"정답!",near?`기준 문장: ${e.item.answer}`:`+${earned} XP · 다음 단계로.`);lockCurrent("계속");animateMascot("celebrate")}
function remediationType(type){return({recall:"typePart",typePart:"cloze",cloze:"order",order:"chunkOrder",chunkOrder:"choose",choose:"expose"}[type]||"expose")}
function queueRemediation(e){if(e.depth>=1)return;const easier=remediationType(e.type),key=`${e.itemId}-${e.type}-${easier}`;if(state.session.remediationKeys.has(key))return;state.session.remediationKeys.add(key);state.session.queue.push(makeExercise(easier,e.item,1))}
function handleIncorrect(score){const s=state.session,e=s.current;s.feedbackOpen=true;s.lives=Math.max(0,s.lives-1);$("#lessonLives").textContent=s.lives;s.missedIds.add(e.itemId);trackAttempt(e.itemId,false,e.type);queueRemediation(e);const pct=Math.max(0,Math.round(score*100));showFeedback("incorrect","괜찮아, 더 쉬운 형태로 다시 나옴",`${e.type==="choose"?"정답":`${pct}% 일치`} · ${e.item.answer}`);lockCurrent("계속");animateMascot("oops")}
function showFeedback(type,title,text){$("#feedback").classList.remove("is-hidden");$("#lessonFooter").classList.remove("correct","incorrect");$("#lessonFooter").classList.add(type);$("#feedbackTitle").textContent=title;$("#feedbackText").textContent=text;$(".feedback-icon").textContent=type==="correct"?"✓":"×"}
function lockCurrent(label){$("#checkButton").disabled=false;$("#checkButton").textContent=label;$("#hintButton").disabled=true;$("#revealButton").disabled=true;$("#exerciseBody").querySelectorAll("button,textarea").forEach(c=>{c.disabled=true})}
function nextExercise(){state.session.position++;renderExercise()}
function fillSequenceHint(){const ui=state.session.ui,n=ui.selected.length;if(n>=ui.targetTokens.length)return;const desired=ui.targetTokens[n].text,candidate=ui.bank.find(t=>t.text===desired&&!ui.selected.includes(t.id));if(candidate)ui.selected.push(candidate.id);$("#checkButton").disabled=ui.selected.length!==ui.targetTokens.length;renderSequenceBoard()}
function fillClozeHint(){const ui=state.session.ui,slot=ui.selected.length;if(slot>=ui.hiddenIndices.length)return;const desired=ui.words[ui.hiddenIndices[slot]],candidate=ui.bank.find(t=>t.text===desired&&!ui.selected.includes(t.id));if(candidate)ui.selected.push(candidate.id);$("#checkButton").disabled=ui.selected.length!==ui.hiddenIndices.length;renderClozeBoard()}
function revealHint(){const s=state.session;if(!s?.current||s.feedbackOpen)return;s.currentHadHelp=true;const e=s.current;if(e.type==="chunkOrder"||e.type==="order"){fillSequenceHint();$("#hintBox").textContent=e.type==="chunkOrder"?"첫 문장 덩어리를 넣어줬음.":"문장 맨 앞에서부터 맞는 단어 하나를 넣어줬음."}else if(e.type==="cloze"){fillClozeHint();$("#hintBox").textContent="다음 빈칸에 들어갈 단어 하나를 넣어줬음."}else if(e.type==="choose")$("#hintBox").textContent=`정답은 “${wordsOf(e.item.answer).slice(0,3).join(" ")} ...”로 시작함.`;else if(e.type==="typePart")$("#hintBox").textContent=`입력할 부분 시작: ${wordsOf(s.ui.expected).slice(0,2).join(" ")} ...`;else $("#hintBox").textContent=`정답 시작: ${wordsOf(e.item.answer).slice(0,3).join(" ")} ...`;$("#hintBox").classList.remove("is-hidden")}
function revealAnswer(){const s=state.session;if(!s?.current||s.feedbackOpen)return;const e=s.current;s.currentHadHelp=true;s.missedIds.add(e.itemId);trackAttempt(e.itemId,false,e.type);queueRemediation(e);s.feedbackOpen=true;showFeedback("incorrect","정답을 보고 한 번 더 익혀",e.item.answer);lockCurrent("봤으면 계속");animateMascot("oops")}
function animateMascot(cls){const m=$("#lessonMascot");m.classList.remove("celebrate","oops");void m.offsetWidth;m.classList.add(cls);setTimeout(()=>m.classList.remove(cls),600)}

function finishLesson(){const s=state.session,p=getCourseProgress(),isPath=state.path.some(l=>l.id===s.lesson.id);if(isPath&&!p.completedLessons.includes(s.lesson.id))p.completedLessons.push(s.lesson.id);const today=localDateKey();p.daily[today]=Number(p.daily[today]||0)+1;persistProgress();saveGlobalCompletion(s.sessionXp);const course=activeCourse(),missed=course.items.filter(i=>s.missedIds.has(i.id)),accuracy=s.initialGradedCount?Math.round(s.firstTryCorrect/s.initialGradedCount*100):100;state.lastResult={lessonId:s.lesson.id,missedIds:missed.map(i=>i.id),accuracy,xp:s.sessionXp,isPathLesson:isPath};$("#xpStat").textContent=s.sessionXp;$("#accuracyStat").textContent=`${accuracy}%`;$("#missedStat").textContent=missed.length;$("#resultMessage").textContent=accuracy===100?"이번 단계는 완벽함. 다음 단계에서는 도움을 더 줄여도 됨.":accuracy>=75?"거의 됐음. 틀린 문장은 더 쉬운 유형으로 한 번 더 복습했음.":"아직 어려운 부분은 정상임. 다음 레슨에서도 같은 문장이 다른 방식으로 다시 나옴.";const list=$("#missedList");list.innerHTML="";missed.forEach((item,index)=>{const row=document.createElement("div");row.className="missed-item";row.innerHTML=`<span class="missed-index">${index+1}</span><div><strong>${escapeHtml(item.cue||makeCue(item.question))}</strong><p>${escapeHtml(item.answer)}</p></div>`;list.appendChild(row)});$("#missedPanel").classList.toggle("is-hidden",!missed.length);$("#retryMissed").classList.toggle("is-hidden",!missed.length);$("#continuePath").textContent=isPath?"다음 단계":"학습 경로로";$("#progressBar").style.width="100%";switchScreen($("#resultScreen"))}
function retryMissed(){const ids=state.lastResult?.missedIds||[];if(!ids.length)return;const items=activeCourse().items.filter(i=>ids.includes(i.id)),lesson={id:`retry-${Date.now()}`,kind:"practice",practiceType:"weak",color:"blue",icon:"bolt",overline:"REVIEW",title:"막힌 문장 다시",description:"현재 숙련도보다 한 단계 쉬운 문제부터 다시 연결.",itemIds:ids};startLesson(lesson,items)}
function continuePath(){if(!state.lastResult?.isPathLesson){switchScreen($("#homeScreen"));renderHome();return}const i=state.path.findIndex(l=>l.id===state.lastResult.lessonId),next=state.path[i+1];switchScreen($("#homeScreen"));renderHome();if(next)setTimeout(()=>openLessonSheet(next.id),80)}
function learnedPracticePool(){const course=activeCourse(),p=getCourseProgress(),learned=course.items.filter(i=>Number(p.stage[i.id]||0)>0);return learned.length?learned:course.items.slice(0,Math.min(state.settings.chunkSize,course.items.length))}
function openPracticeHub(){if(activeCourse().items.length)openDialog($("#practiceDialog"))}
function startPractice(type){closeDialog($("#practiceDialog"));let pool=learnedPracticePool();pool=type==="weak"?[...pool].sort((a,b)=>weakScore(b.id)-weakScore(a.id)):orderItems(pool,state.settings.orderMode==="original"?"random":state.settings.orderMode);pool=pool.slice(0,Math.min(5,pool.length));const titles={order:"단어 조립 연습",cloze:"빈칸 연습",recall:"전체 회상 연습",weak:"약한 문장 맞춤 복습"},lesson={id:`practice-${type}-${Date.now()}`,kind:"practice",practiceType:type,color:"blue",icon:"bolt",overline:"PRACTICE",title:titles[type],description:"학습 경로와 별개로 원하는 문제 유형을 집중 연습.",itemIds:pool.map(i=>i.id)};startLesson(lesson,pool)}
function quickPractice(){openPracticeHub()}

function openCourseLibrary(){renderCourseLibrary();openDialog($("#courseLibraryDialog"))}
function renderCourseLibrary(){const list=$("#courseList");list.innerHTML="";state.courses.forEach(course=>{const p=ensureCourseProgress(course.id),learned=course.items.filter(i=>Number(p.stage[i.id]||0)>0).length,item=document.createElement("div");item.className=`course-list-item ${course.id===state.activeCourseId?"is-active":""}`;item.innerHTML=`<div class="course-avatar">${escapeHtml((course.title.trim()[0]||"R").toUpperCase())}</div><div class="course-list-copy"><strong>${escapeHtml(course.title)}</strong><span>${course.items.length}문장 · ${learned}개 학습 시작 · ${course.builtIn?"기본 제공":"내 세트"}</span></div><div class="course-list-actions"><button class="activate-course" data-course-id="${course.id}" type="button">${course.id===state.activeCourseId?"사용 중":"선택"}</button><button class="edit-course" data-course-id="${course.id}" type="button">편집</button></div>`;list.appendChild(item)});$$(".activate-course").forEach(b=>b.addEventListener("click",()=>activateCourse(b.dataset.courseId)));$$(".edit-course").forEach(b=>b.addEventListener("click",()=>openCourseEditor(b.dataset.courseId)))}
function activateCourse(id){if(!state.courses.some(c=>c.id===id))return;state.activeCourseId=id;localStorage.setItem(STORE.activeCourse,id);ensureCourseProgress(id);closeDialog($("#courseLibraryDialog"));renderHome()}
function openCourseEditor(id=null){const source=id?state.courses.find(c=>c.id===id):null;state.editingCourseId=id;state.editorItems=source?clone(source.items):[{id:uid("item"),cue:"",question:"",answer:"",meaning:""}];$("#editorHeading").textContent=source?"문장 세트 편집":"문장 세트 만들기";$("#courseTitleInput").value=source?.title||"";$("#courseDescriptionInput").value=source?.description||"";$("#deleteCourseButton").classList.toggle("is-hidden",!source||source.builtIn);$("#editorError").classList.add("is-hidden");setEditorTab("cards");renderSentenceEditor();closeDialog($("#courseLibraryDialog"));openDialog($("#courseEditorDialog"))}
function renderSentenceEditor(){const list=$("#sentenceEditorList");list.innerHTML="";state.editorItems.forEach((item,index)=>{const card=document.createElement("section");card.className="sentence-editor-card";card.dataset.itemId=item.id;card.innerHTML=`<div class="sentence-card-head"><span class="sentence-number">${index+1}</span><strong>문장 ${index+1}</strong><button class="move-button move-up" type="button" ${index===0?"disabled":""}>↑</button><button class="move-button move-down" type="button" ${index===state.editorItems.length-1?"disabled":""}>↓</button><button class="remove-sentence" type="button">×</button></div><div class="sentence-fields"><label>화면에 보여줄 질문<textarea data-field="question" placeholder="예: What technology are you interested in?">${escapeHtml(item.question)}</textarea></label><label>짧은 힌트 · 선택<textarea data-field="cue" placeholder="비우면 질문 앞 5단어 자동 생성">${escapeHtml(item.cue||"")}</textarea></label><label>뜻 / 추가 설명 · 선택<textarea data-field="meaning" placeholder="처음 익힐 때 함께 보여줄 설명">${escapeHtml(item.meaning||"")}</textarea></label><label>최종적으로 외울 문장<textarea data-field="answer" placeholder="학습자가 마지막 단계에서 직접 회상할 정답">${escapeHtml(item.answer)}</textarea></label></div>`;list.appendChild(card)});list.querySelectorAll("textarea[data-field]").forEach(t=>t.addEventListener("input",e=>updateEditorItem(e.currentTarget)));list.querySelectorAll(".move-up").forEach(b=>b.addEventListener("click",()=>moveEditorItem(b.closest(".sentence-editor-card").dataset.itemId,-1)));list.querySelectorAll(".move-down").forEach(b=>b.addEventListener("click",()=>moveEditorItem(b.closest(".sentence-editor-card").dataset.itemId,1)));list.querySelectorAll(".remove-sentence").forEach(b=>b.addEventListener("click",()=>removeEditorItem(b.closest(".sentence-editor-card").dataset.itemId)))}
function updateEditorItem(t){const card=t.closest(".sentence-editor-card"),item=state.editorItems.find(x=>x.id===card.dataset.itemId);if(item)item[t.dataset.field]=t.value}
function moveEditorItem(id,delta){const i=state.editorItems.findIndex(x=>x.id===id),j=i+delta;if(i<0||j<0||j>=state.editorItems.length)return;[state.editorItems[i],state.editorItems[j]]=[state.editorItems[j],state.editorItems[i]];renderSentenceEditor()}
function removeEditorItem(id){if(state.editorItems.length===1)return;state.editorItems=state.editorItems.filter(i=>i.id!==id);renderSentenceEditor()}
function addEditorItem(){state.editorItems.push({id:uid("item"),cue:"",question:"",answer:"",meaning:""});renderSentenceEditor();const cards=$$(".sentence-editor-card");cards[cards.length-1]?.scrollIntoView({behavior:"smooth",block:"center"})}
function setEditorTab(tab){$$(".editor-tab").forEach(b=>b.classList.toggle("is-active",b.dataset.editorTab===tab));$("#cardsEditorPanel").classList.toggle("is-hidden",tab!=="cards");$("#bulkEditorPanel").classList.toggle("is-hidden",tab!=="bulk");if(tab==="bulk")$("#bulkInput").value=serializeBulk(state.editorItems)}
function serializeBulk(items){return items.map(i=>[`Q: ${i.question}`,`CUE: ${i.cue||makeCue(i.question)}`,`A: ${i.answer}`,i.meaning?`MEANING: ${i.meaning}`:""].filter(Boolean).join("\n")).join("\n---\n")}
function parseBulk(text){const blocks=text.split(/^\s*---\s*$/m).map(b=>b.trim()).filter(Boolean);if(!blocks.length)throw new Error("입력된 문장이 없음.");return blocks.map((block,index)=>{const data={question:"",cue:"",answer:"",meaning:""};let current=null;block.split(/\r?\n/).forEach(line=>{const m=line.match(/^\s*(Q|QUESTION|CUE|A|ANSWER|M|MEANING)\s*:\s*(.*)$/i);if(m){const key=m[1].toUpperCase();current=key==="Q"||key==="QUESTION"?"question":key==="CUE"?"cue":key==="M"||key==="MEANING"?"meaning":"answer";data[current]=m[2].trim()}else if(current&&line.trim())data[current]+=`${data[current]?" ":""}${line.trim()}`});if(!data.question||!data.answer)throw new Error(`${index+1}번째 블록에 질문(Q) 또는 정답(A)이 비어 있음.`);if(!data.cue)data.cue=makeCue(data.question);return{id:uid("item"),...data}})}
function applyBulk(){try{state.editorItems=parseBulk($("#bulkInput").value);$("#editorError").classList.add("is-hidden");setEditorTab("cards");renderSentenceEditor()}catch(error){showEditorError(error.message)}}
function showEditorError(message){$("#editorError").textContent=message;$("#editorError").classList.remove("is-hidden")}
function saveCourse(){const title=$("#courseTitleInput").value.trim(),description=$("#courseDescriptionInput").value.trim(),items=state.editorItems.map(i=>({...i,question:i.question.trim(),cue:(i.cue||makeCue(i.question)).trim(),answer:i.answer.trim(),meaning:(i.meaning||"").trim()}));if(!title)return showEditorError("세트 이름을 입력해야 함.");if(!items.length||items.some(i=>!i.question||!i.answer))return showEditorError("모든 문장에 화면에 보여줄 질문과 최종 정답이 필요함.");const existing=state.courses.find(c=>c.id===state.editingCourseId);if(existing?.builtIn){const course={id:uid("course"),title:`${title} 복사본`,description,builtIn:false,items:items.map(i=>({...i,id:uid("item")}))};state.courses.push(course);state.activeCourseId=course.id}else if(existing){existing.title=title;existing.description=description;existing.items=items}else{const course={id:uid("course"),title,description,builtIn:false,items};state.courses.push(course);state.activeCourseId=course.id}localStorage.setItem(STORE.activeCourse,state.activeCourseId);persistCourses();ensureCourseProgress(state.activeCourseId);closeDialog($("#courseEditorDialog"));renderHome()}
function deleteCurrentCourse(){const course=state.courses.find(c=>c.id===state.editingCourseId);if(!course||course.builtIn)return;state.courses=state.courses.filter(c=>c.id!==course.id);delete state.progressByCourse[course.id];if(state.activeCourseId===course.id)state.activeCourseId=DEFAULT_COURSE.id;localStorage.setItem(STORE.activeCourse,state.activeCourseId);persistCourses();persistProgress();closeDialog($("#courseEditorDialog"));renderHome()}
function openOrderSettings(){$$("input[name='learningMode']").forEach(i=>{i.checked=i.value===state.settings.learningMode});$$("input[name='orderMode']").forEach(i=>{i.checked=i.value===state.settings.orderMode});$$("input[name='chunkSize']").forEach(i=>{i.checked=Number(i.value)===Number(state.settings.chunkSize)});openDialog($("#orderDialog"))}
function saveOrderSettings(){state.settings={learningMode:$("input[name='learningMode']:checked")?.value||"beginner",orderMode:$("input[name='orderMode']:checked")?.value||"original",chunkSize:Number($("input[name='chunkSize']:checked")?.value||2)};persistSettings();closeDialog($("#orderDialog"));renderHome()}
function stageLabel(stage){return stage>=5?"전체 회상":stage===4?"부분 회상":stage===3?"빈칸 가능":stage===2?"조립 가능":stage===1?"익히는 중":"미학습"}
function openStats(){const p=getCourseProgress(),course=activeCourse();$("#statsCourseName").textContent=course.title;$("#statsXp").textContent=getGlobalStats().totalXp;$("#statsLessons").textContent=validCompletedLessonIds().length;$("#statsWeak").textContent=Object.values(p.weak).filter(v=>Number(v)>0).length;const list=$("#sentenceStatsList");list.innerHTML="";course.items.forEach((item,index)=>{const attempts=Number(p.attempts[item.id]||0),weak=Number(p.weak[item.id]||0),stage=Number(p.stage[item.id]||0),row=document.createElement("div");row.className=`sentence-stat-row ${weak>0?"weak":stage>=4?"mastered":""}`;row.innerHTML=`<span class="status-dot">${index+1}</span><div><strong>${escapeHtml(item.cue||makeCue(item.question))}</strong><small>${stageLabel(stage)} · ${attempts?`${attempts}회 채점`:"아직 채점 전"}</small></div><span class="sentence-stat-score">${weak>0?`약함 ${weak}`:stage>=5?"✓ 실전":stage?`Lv.${stage}`:"—"}</span>`;list.appendChild(row)});openDialog($("#statsDialog"))}
function handleNav(target){if(target==="sets")return openCourseLibrary();if(target==="practice")return openPracticeHub();if(target==="stats")return openStats();switchScreen($("#homeScreen"));renderHome()}
function toggleFullQuestion(){const full=$("#fullQuestion"),hidden=full.classList.toggle("is-hidden");$("#fullQuestionToggle").textContent=hidden?"전체 질문 보기":"전체 질문 숨기기"}
function exitToHome(){closeDialog($("#exitDialog"));state.session=null;switchScreen($("#homeScreen"));renderHome()}
function bindEvents(){$("#courseSwitcherMobile").addEventListener("click",openCourseLibrary);$("#courseMenuButton").addEventListener("click",openCourseLibrary);$("#openOrderSettings").addEventListener("click",openOrderSettings);$("#quickPractice").addEventListener("click",quickPractice);$("#railSettings").addEventListener("click",openOrderSettings);$$("[data-nav]").forEach(b=>b.addEventListener("click",()=>handleNav(b.dataset.nav)));$$("[data-close-dialog]").forEach(b=>b.addEventListener("click",()=>closeDialog(b.closest("dialog"))));$("#closeLessonSheet").addEventListener("click",()=>closeDialog($("#lessonSheet")));$("#startLessonFromSheet").addEventListener("click",startSelectedLesson);$("#createCourseButton").addEventListener("click",()=>openCourseEditor());$("#addSentenceButton").addEventListener("click",addEditorItem);$$(".editor-tab").forEach(b=>b.addEventListener("click",()=>setEditorTab(b.dataset.editorTab)));$("#applyBulkButton").addEventListener("click",applyBulk);$("#saveCourseButton").addEventListener("click",saveCourse);$("#cancelCourseEdit").addEventListener("click",()=>closeDialog($("#courseEditorDialog")));$("#deleteCourseButton").addEventListener("click",deleteCurrentCourse);$("#saveOrderSettings").addEventListener("click",saveOrderSettings);$$("[data-practice]").forEach(b=>b.addEventListener("click",()=>startPractice(b.dataset.practice)));$("#checkButton").addEventListener("click",checkCurrentExercise);$("#hintButton").addEventListener("click",revealHint);$("#revealButton").addEventListener("click",revealAnswer);$("#fullQuestionToggle").addEventListener("click",toggleFullQuestion);$("#exitLesson").addEventListener("click",()=>openDialog($("#exitDialog")));$("#keepLearning").addEventListener("click",()=>closeDialog($("#exitDialog")));$("#confirmExit").addEventListener("click",exitToHome);$("#retryMissed").addEventListener("click",retryMissed);$("#continuePath").addEventListener("click",continuePath);$("#backHome").addEventListener("click",()=>{switchScreen($("#homeScreen"));renderHome()})}

loadState();bindEvents();renderHome();