const DEFAULT_COURSE={id:"future-tech-speaking",title:"Future Technology Speaking",description:"질문 앞부분을 보고 답변을 정확하게 떠올리는 연습",builtIn:true,items:[
{id:"q1",cue:"What specific future technology...",question:"What specific future technology or innovation are you most interested in exploring, and why?",answer:"I am interested in AI because it can make our lives easier."},
{id:"q2",cue:"How has a specific piece...",question:"How has a specific piece of modern technology significantly changed your daily routine or habits?",answer:"My smartphone changed my daily life because it makes many things easier."},
{id:"q3",cue:"Do you think technological advancements...",question:"Do you think technological advancements make human connections stronger or more isolated?",answer:"I think technology makes human connections stronger because we can communicate more easily."},
{id:"q4",cue:"In what ways do you think automation...",question:"In what ways do you think automation and AI will impact the future job market?",answer:"I think AI will replace some jobs, but it will also create new jobs."},
{id:"q5",cue:"What is the most serious ethical...",question:"What is the most serious ethical concern regarding the rapid development of biotechnology or AI?",answer:"The biggest problem is that AI may use personal information without permission."},
{id:"q6",cue:"How can society address the digital...",question:"How can society address the digital divide between generations or different economic classes?",answer:"Society should give free digital lessons and cheaper devices to everyone."},
{id:"q7",cue:"How does this technological issue...",question:"How does this technological issue relate to your future academic major or dream career?",answer:"This issue relates to my future computer science major because I want to build useful technology."},
{id:"q8",cue:"If you become a professional...",question:"If you become a professional in your field, what innovative solution would you like to introduce?",answer:"If I become a software engineer, I want to create safe AI tools for everyone."},
{id:"q9",cue:"What interdisciplinary knowledge...",question:"What interdisciplinary knowledge do you think is necessary to tackle complex modern technology problems?",answer:"We need knowledge of technology, science, math, and communication to solve problems."},
{id:"q10",cue:"Are you generally optimistic or pessimistic...",question:"Are you generally optimistic or pessimistic about living in a heavily tech-driven future society?",answer:"I am optimistic because technology can make our lives easier and better."},
{id:"q11",cue:"What is your final message...",question:"What is your final message on how humans should coexist with advanced technology?",answer:"Humans should use advanced technology wisely and always keep people in control."}]};

const STORE={courses:"recallRushCoursesV2",activeCourse:"recallRushActiveCourseV2",settings:"recallRushSettingsV2",progress:"recallRushProgressV2",xp:"recallRushXp",activity:"recallRushActivity",sessions:"recallRushSessions"};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],clone=v=>JSON.parse(JSON.stringify(v));
const safeJson=(v,f)=>{try{return v?JSON.parse(v):f}catch{return f}};
const escapeHtml=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const state={courses:[],activeCourseId:null,settings:{orderMode:"original",chunkSize:3},progressByCourse:{},path:[],selectedLessonId:null,editingCourseId:null,editorItems:[],session:null,lastResult:null};

function uid(prefix="id"){return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`}
function localDateKey(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}
function loadState(){const stored=safeJson(localStorage.getItem(STORE.courses),[]);state.courses=[clone(DEFAULT_COURSE),...stored.filter(c=>c&&c.id!==DEFAULT_COURSE.id)];state.activeCourseId=localStorage.getItem(STORE.activeCourse)||DEFAULT_COURSE.id;if(!state.courses.some(c=>c.id===state.activeCourseId))state.activeCourseId=DEFAULT_COURSE.id;state.settings={...state.settings,...safeJson(localStorage.getItem(STORE.settings),{})};state.progressByCourse=safeJson(localStorage.getItem(STORE.progress),{});ensureCourseProgress(activeCourse().id)}
function persistCourses(){localStorage.setItem(STORE.courses,JSON.stringify(state.courses.filter(c=>c.id!==DEFAULT_COURSE.id)))}
function persistProgress(){localStorage.setItem(STORE.progress,JSON.stringify(state.progressByCourse))}
function persistSettings(){localStorage.setItem(STORE.settings,JSON.stringify(state.settings))}
function activeCourse(){return state.courses.find(c=>c.id===state.activeCourseId)||state.courses[0]}
function ensureCourseProgress(id){if(!state.progressByCourse[id])state.progressByCourse[id]={completedLessons:[],weak:{},attempts:{},mastered:{},daily:{}};const p=state.progressByCourse[id];p.completedLessons||=[];p.weak||={};p.attempts||={};p.mastered||={};p.daily||={};return p}
function getCourseProgress(){return ensureCourseProgress(activeCourse().id)}
function getGlobalStats(){const totalXp=Number(localStorage.getItem(STORE.xp)||0),a=safeJson(localStorage.getItem(STORE.activity),{}),today=localDateKey(),yesterday=localDateKey(new Date(Date.now()-86400000));let streak=Number(a.streak||0);if(a.lastDate&&a.lastDate!==today&&a.lastDate!==yesterday)streak=0;return{totalXp,streak}}
function saveGlobalCompletion(xp){localStorage.setItem(STORE.xp,String(Number(localStorage.getItem(STORE.xp)||0)+xp));localStorage.setItem(STORE.sessions,String(Number(localStorage.getItem(STORE.sessions)||0)+1));const a=safeJson(localStorage.getItem(STORE.activity),{}),today=localDateKey(),yesterday=localDateKey(new Date(Date.now()-86400000));let streak=Number(a.streak||0);if(a.lastDate!==today)streak=a.lastDate===yesterday?streak+1:1;localStorage.setItem(STORE.activity,JSON.stringify({lastDate:today,streak}))}
function makeCue(q){const words=String(q||"").trim().split(/\s+/).filter(Boolean);return words.length?`${words.slice(0,Math.min(5,words.length)).join(" ")}${words.length>5?"...":""}`:""}
function shuffle(items){const c=[...items];for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]]}return c}
function weakScore(id){return Number(getCourseProgress().weak[id]||0)}
function orderItems(items,mode=state.settings.orderMode){const copy=[...items];if(mode==="random")return shuffle(copy);if(mode==="weak")return copy.sort((a,b)=>weakScore(b.id)-weakScore(a.id));return copy}

function buildPath(course=activeCourse()){const items=course.items||[],chunkSize=Math.max(2,Math.min(4,Number(state.settings.chunkSize)||3)),lessons=[],learned=[];let n=1;for(let start=0;start<items.length;start+=chunkSize){const chunk=items.slice(start,start+chunkSize),ids=chunk.map(i=>i.id);lessons.push({id:`learn-${start}`,kind:"learn",color:"green",icon:"star",overline:`LESSON ${n++}`,title:`새 문장 ${start+1}–${start+chunk.length}`,description:"새 질문과 답을 처음 연결하는 단계.",itemIds:ids,xpPerItem:10});learned.push(...ids);lessons.push({id:`review-${start}`,kind:"review",color:"blue",icon:"bolt",overline:`LESSON ${n++}`,title:`복습 ${start+1}–${start+chunk.length}`,description:"방금 배운 문장을 순서 없이 다시 꺼내기.",itemIds:[...ids],xpPerItem:12});if(start+chunkSize<items.length&&learned.length>=chunkSize*2&&learned.length%(chunkSize*2)===0)lessons.push({id:`checkpoint-${start}`,kind:"checkpoint",color:"purple",icon:"check",overline:"CHECKPOINT",title:`${learned.length}문장 중간 점검`,description:"지금까지 배운 문장을 섞어서 확인.",itemIds:[...learned],maxItems:Math.min(6,learned.length),xpPerItem:14})}if(items.length)lessons.push({id:"final-random",kind:"final",color:"gold",icon:"star",overline:"FINAL TEST",title:"실전 랜덤 5",description:"전체 문장에서 5개를 랜덤으로 뽑는 최종 점검.",itemIds:items.map(i=>i.id),maxItems:Math.min(5,items.length),xpPerItem:16});return lessons}
function lessonItems(lesson){const course=activeCourse();let items=lesson.itemIds.map(id=>course.items.find(i=>i.id===id)).filter(Boolean),force=["review","checkpoint","final"].includes(lesson.kind);items=orderItems(items,force&&state.settings.orderMode==="original"?"random":state.settings.orderMode);return lesson.maxItems&&items.length>lesson.maxItems?items.slice(0,lesson.maxItems):items}
function completedSet(){return new Set(getCourseProgress().completedLessons)}
function firstIncompleteIndex(){const d=completedSet(),i=state.path.findIndex(l=>!d.has(l.id));return i===-1?Math.max(0,state.path.length-1):i}
function isLessonUnlocked(i){if(i===0)return true;const d=completedSet();return d.has(state.path[i-1].id)||d.has(state.path[i].id)}

function renderHome(){const c=activeCourse();ensureCourseProgress(c.id);state.path=buildPath(c);$("#courseTitle").textContent=c.title;$("#courseDescription").textContent=c.description||`${c.items.length}개 문장을 단계별로 암기`;$("#courseLabel").textContent=c.builtIn?"STARTER COURSE":"MY COURSE";$("#mobileCourseTitle").textContent=c.title;$("#mobileCourseInitial").textContent=(c.title.trim()[0]||"R").toUpperCase();$("#courseSentenceCount").textContent=c.items.length;renderPath();renderStats()}
function renderPath(){const stage=$("#pathStage");stage.innerHTML="";if(!state.path.length){stage.innerHTML=`<div class="empty-path"><strong>아직 문장이 없음</strong><p>문장 세트에서 Q / CUE / A를 추가하면 단계별 학습 경로가 자동으로 만들어짐.</p><button class="primary-button" id="emptyAddCourse" type="button">문장 세트 편집</button></div>`;$("#emptyAddCourse").addEventListener("click",()=>openCourseEditor(activeCourse().id));return}const done=completedSet(),current=firstIncompleteIndex();state.path.forEach((lesson,index)=>{if(lesson.kind==="checkpoint"){const d=document.createElement("div");d.className="checkpoint-divider";d.textContent="중간 점검";stage.appendChild(d)}if(index===Math.ceil(state.path.length/2)){const m=document.createElement("div");m.className="path-mascot-row";m.innerHTML=`<img src="assets/mori.svg" alt="모리" class="path-mascot"><div class="mascot-note">한 단계씩 잠금이 풀림. 틀린 문장은 다음 복습에서 더 자주 만나게 됨.</div>`;stage.appendChild(m)}const unlocked=isLessonUnlocked(index),completed=done.has(lesson.id),row=document.createElement("div"),icon=unlocked?(lesson.icon==="bolt"?"i-bolt":lesson.icon==="check"?"i-check":"i-star"):"i-lock";row.className=`path-row pos-${index%4}`;row.innerHTML=`<button class="lesson-node ${lesson.color!=="green"?lesson.color:""} ${completed?"completed":""} ${index===current&&unlocked?"current":""} ${unlocked?"":"locked"}" data-lesson-id="${lesson.id}" type="button" ${unlocked?"":"disabled"}><span class="node-shadow"></span><span class="node-face"><svg><use href="#${icon}"/></svg></span></button><div class="node-caption"><strong>${escapeHtml(lesson.title)}</strong><span>${completed?"완료":unlocked?lesson.overline:"이전 단계 완료 후 열림"}</span></div>`;stage.appendChild(row)});$$(".lesson-node[data-lesson-id]").forEach(b=>b.addEventListener("click",()=>openLessonSheet(b.dataset.lessonId)))}
function renderStats(){const{totalXp,streak}=getGlobalStats();$("#totalXp").textContent=totalXp;$("#totalXpMobile").textContent=totalXp;$("#streakDays").textContent=streak;$("#streakDaysMobile").textContent=streak;const p=getCourseProgress(),completed=p.completedLessons.length,total=state.path.length||1,percent=state.path.length?Math.round(completed/total*100):0;$("#completedLessonCount").textContent=completed;$("#weakCount").textContent=Object.values(p.weak).filter(v=>Number(v)>0).length;$("#masteryPercent").textContent=`${percent}%`;$("#masteryRingText").textContent=`${percent}%`;$(".mastery-ring").style.setProperty("--progress",`${percent*3.6}deg`);$("#masteryLabel").textContent=percent===100?"코스 완료":percent>=50?"절반 이상":percent>0?"진행 중":"시작 전";const today=localDateKey(),daily=Number(p.daily[today]||0);$("#dailyGoalCount").textContent=`${Math.min(2,daily)}/2`;$("#dailyGoalBar").style.width=`${Math.min(100,daily/2*100)}%`;$("#dailyGoalCopy").textContent=daily>=2?"오늘 목표 완료. 더 하면 보너스 복습.":`레슨 ${2-daily}개만 더 끝내면 오늘 목표 완료.`}

function openDialog(d){if(d&&typeof d.showModal==="function"&&!d.open)d.showModal()}function closeDialog(d){if(d?.open)d.close()}
function openLessonSheet(id){const l=state.path.find(x=>x.id===id);if(!l)return;state.selectedLessonId=id;const items=lessonItems(l);$("#lessonSheetOverline").textContent=l.overline;$("#lessonSheetTitle").textContent=l.title;$("#lessonSheetDescription").textContent=l.description;$("#lessonSheetCount").textContent=`${items.length}문장`;$("#lessonSheetXp").textContent=`최대 ${items.length*l.xpPerItem} XP`;const icon=$("#lessonSheetIcon");icon.className=`lesson-sheet-icon ${l.color==="green"?"":l.color}`;icon.innerHTML=`<svg><use href="#${l.icon==="bolt"?"i-bolt":l.icon==="check"?"i-check":"i-star"}"/></svg>`;openDialog($("#lessonSheet"))}
function startSelectedLesson(){const l=state.path.find(x=>x.id===state.selectedLessonId);if(!l)return;closeDialog($("#lessonSheet"));startLesson(l,lessonItems(l))}
function switchScreen(target){[$("#homeScreen"),$("#lessonScreen"),$("#resultScreen")].forEach(s=>s.classList.toggle("is-hidden",s!==target));window.scrollTo({top:0,behavior:"instant"})}
function startLesson(lesson,items){if(!items.length)return;state.session={lesson,queue:items.map(i=>({...i,review:false})),originalCount:items.length,position:0,current:null,firstTryCorrect:0,sessionXp:0,lives:5,feedbackOpen:false,currentHadHelp:false,missedIds:new Set};switchScreen($("#lessonScreen"));$("#lessonKindLabel").textContent=lesson.overline;$("#lessonTitle").textContent=lesson.title;renderQuestion()}
function renderQuestion(){const s=state.session;if(!s||s.position>=s.queue.length)return finishLesson();s.current=s.queue[s.position];s.feedbackOpen=false;s.currentHadHelp=false;$("#answerInput").value="";$("#answerInput").disabled=false;$("#hintBox").classList.add("is-hidden");$("#fullQuestion").classList.add("is-hidden");$("#fullQuestionToggle").textContent="전체 질문 보기";$("#feedback").classList.add("is-hidden");$("#lessonFooter").classList.remove("correct","incorrect");$("#checkButton").disabled=true;$("#checkButton").textContent="확인";$("#hintButton").disabled=false;$("#revealButton").disabled=false;$("#questionCue").textContent=s.current.cue||makeCue(s.current.question);$("#fullQuestion").textContent=s.current.question;$("#questionCounter").textContent=`${Math.min(s.position+1,s.originalCount)} / ${s.originalCount}${s.current.review?" · 다시":""}`;$("#lessonLives").textContent=s.lives;$("#progressBar").style.width=`${s.originalCount?Math.min(s.position,s.originalCount)/s.originalCount*100:0}%`;setTimeout(()=>$("#answerInput").focus({preventScroll:true}),60)}
function normalize(t){return String(t).toLowerCase().replace(/[’‘]/g,"'").replace(/[^a-z0-9'\s]/g," ").replace(/\s+/g," ").trim()}
function levenshtein(a,b){const m=Array.from({length:a.length+1},(_,i)=>[i]);for(let j=0;j<=b.length;j++)m[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++){const c=a[i-1]===b[j-1]?0:1;m[i][j]=Math.min(m[i-1][j]+1,m[i][j-1]+1,m[i-1][j-1]+c)}return m[a.length][b.length]}
function similarity(a,b){const x=normalize(a),y=normalize(b);return!x||!y?0:1-levenshtein(x,y)/Math.max(x.length,y.length)}
function trackAttempt(id,correct){const p=getCourseProgress();p.attempts[id]=Number(p.attempts[id]||0)+1;if(correct){p.mastered[id]=Number(p.mastered[id]||0)+1;p.weak[id]=Math.max(0,Number(p.weak[id]||0)-1)}else p.weak[id]=Number(p.weak[id]||0)+2;persistProgress()}
function checkAnswer(){const s=state.session;if(!s)return;if(s.feedbackOpen)return nextQuestion();const typed=$("#answerInput").value.trim();if(!typed)return;const score=similarity(typed,s.current.answer),exact=normalize(typed)===normalize(s.current.answer);exact||score>=.93?handleCorrect(exact,score):handleIncorrect(score)}
function handleCorrect(exact,score){const s=state.session;s.feedbackOpen=true;const clean=!s.current.review&&!s.currentHadHelp&&!s.missedIds.has(s.current.id);if(clean)s.firstTryCorrect++;const earned=s.currentHadHelp?5:s.current.review?8:s.lesson.xpPerItem;s.sessionXp+=earned;trackAttempt(s.current.id,true);showFeedback("correct",!exact&&score<.985?"거의 정확해!":"정답!",!exact&&score<.985?`기준 답변: ${s.current.answer}`:`+${earned} XP · 그대로 다음 문제로 연결.`);lockExercise("계속");animateMascot("celebrate")}
function handleIncorrect(score){const s=state.session;s.feedbackOpen=true;s.lives=Math.max(0,s.lives-1);$("#lessonLives").textContent=s.lives;s.missedIds.add(s.current.id);ensureReviewQueued(s.current);trackAttempt(s.current.id,false);showFeedback("incorrect","다시 연결하자",`${Math.max(0,Math.round(score*100))}% 일치 · ${s.current.answer}`);lockExercise("계속");animateMascot("oops")}
function ensureReviewQueued(item){const s=state.session;if(!s.queue.slice(s.position+1).some(x=>x.id===item.id&&x.review))s.queue.push({...item,review:true})}
function showFeedback(type,title,text){$("#feedback").classList.remove("is-hidden");$("#lessonFooter").classList.remove("correct","incorrect");$("#lessonFooter").classList.add(type);$("#feedbackTitle").textContent=title;$("#feedbackText").textContent=text;$(".feedback-icon").textContent=type==="correct"?"✓":"×"}
function lockExercise(label){$("#answerInput").disabled=true;$("#checkButton").disabled=false;$("#checkButton").textContent=label;$("#hintButton").disabled=true;$("#revealButton").disabled=true}
function nextQuestion(){state.session.position++;renderQuestion()}
function revealHint(){const s=state.session;if(!s?.current||s.feedbackOpen)return;s.currentHadHelp=true;const words=s.current.answer.replace(/[.,]/g,"").split(/\s+/),amount=Math.min(4,Math.max(2,Math.ceil(words.length*.22)));$("#hintBox").textContent=`시작 힌트: ${words.slice(0,amount).join(" ")} ...`;$("#hintBox").classList.remove("is-hidden")}
function revealAnswer(){const s=state.session;if(!s?.current||s.feedbackOpen)return;s.currentHadHelp=true;s.missedIds.add(s.current.id);ensureReviewQueued(s.current);trackAttempt(s.current.id,false);$("#answerInput").value=s.current.answer;s.feedbackOpen=true;showFeedback("incorrect","정답을 보고 다시 외워",s.current.answer);lockExercise("외웠으면 계속");animateMascot("oops")}
function animateMascot(c){const m=$("#lessonMascot");m.classList.remove("celebrate","oops");void m.offsetWidth;m.classList.add(c);setTimeout(()=>m.classList.remove(c),600)}
function finishLesson(){const s=state.session,p=getCourseProgress();if(!p.completedLessons.includes(s.lesson.id))p.completedLessons.push(s.lesson.id);const today=localDateKey();p.daily[today]=Number(p.daily[today]||0)+1;persistProgress();saveGlobalCompletion(s.sessionXp);const course=activeCourse(),missed=course.items.filter(i=>s.missedIds.has(i.id)),accuracy=s.originalCount?Math.round(s.firstTryCorrect/s.originalCount*100):0;state.lastResult={lessonId:s.lesson.id,missedIds:missed.map(i=>i.id),accuracy,xp:s.sessionXp};$("#xpStat").textContent=s.sessionXp;$("#accuracyStat").textContent=`${accuracy}%`;$("#missedStat").textContent=missed.length;$("#resultMessage").textContent=accuracy===100?"완벽하게 연결됨. 다음 단계로 넘어가도 됨.":accuracy>=80?"거의 끝. 막힌 문장만 복습하면 됨.":accuracy>=50?"기억 연결이 생김. 바로 다음 복습 단계에서 다시 굳히자.":"아직 약한 문장이 많음. 틀린 문장부터 한 번 더 돌리는 게 빠름.";const list=$("#missedList");list.innerHTML="";missed.forEach((item,i)=>{const row=document.createElement("div");row.className="missed-item";row.innerHTML=`<span class="missed-index">${i+1}</span><div><strong>${escapeHtml(item.cue||makeCue(item.question))}</strong><p>${escapeHtml(item.answer)}</p></div>`;list.appendChild(row)});$("#missedPanel").classList.toggle("is-hidden",!missed.length);$("#retryMissed").classList.toggle("is-hidden",!missed.length);switchScreen($("#resultScreen"))}
function retryMissed(){const ids=state.lastResult?.missedIds||[];if(!ids.length)return;const lesson={id:`retry-${Date.now()}`,kind:"review",color:"blue",icon:"bolt",overline:"REVIEW",title:"틀린 문장 다시",description:"방금 막힌 문장만 다시 확인.",itemIds:ids,xpPerItem:8};startLesson(lesson,lessonItems(lesson))}
function continuePath(){const i=state.path.findIndex(l=>l.id===state.lastResult?.lessonId),next=state.path[i+1];switchScreen($("#homeScreen"));renderHome();if(next)setTimeout(()=>openLessonSheet(next.id),80)}
function quickPractice(){const course=activeCourse();if(!course.items.length)return;const p=getCourseProgress(),done=new Set(p.completedLessons),learned=new Set();state.path.forEach(l=>{if(done.has(l.id))l.itemIds.forEach(id=>learned.add(id))});let pool=course.items.filter(i=>learned.has(i.id));if(!pool.length)pool=course.items.slice(0,Math.min(5,course.items.length));pool=orderItems(pool,Object.keys(p.weak||{}).length?"weak":"random").slice(0,Math.min(5,pool.length));startLesson({id:`quick-${Date.now()}`,kind:"review",color:"blue",icon:"bolt",overline:"QUICK PRACTICE",title:"빠른 복습",description:"배운 문장 중 5개 확인.",itemIds:pool.map(i=>i.id),xpPerItem:8},pool)}

function openCourseLibrary(){renderCourseLibrary();openDialog($("#courseLibraryDialog"))}
function renderCourseLibrary(){const list=$("#courseList");list.innerHTML="";state.courses.forEach(c=>{const item=document.createElement("div");item.className=`course-list-item ${c.id===state.activeCourseId?"is-active":""}`;item.innerHTML=`<div class="course-avatar">${escapeHtml((c.title.trim()[0]||"R").toUpperCase())}</div><div class="course-list-copy"><strong>${escapeHtml(c.title)}</strong><span>${c.items.length}문장 · ${c.builtIn?"기본 제공":"내 세트"}</span></div><div class="course-list-actions"><button class="activate-course" data-course-id="${c.id}" type="button">${c.id===state.activeCourseId?"사용 중":"선택"}</button><button class="edit-course" data-course-id="${c.id}" type="button">편집</button></div>`;list.appendChild(item)});$$(".activate-course").forEach(b=>b.addEventListener("click",()=>activateCourse(b.dataset.courseId)));$$(".edit-course").forEach(b=>b.addEventListener("click",()=>openCourseEditor(b.dataset.courseId)))}
function activateCourse(id){if(!state.courses.some(c=>c.id===id))return;state.activeCourseId=id;localStorage.setItem(STORE.activeCourse,id);ensureCourseProgress(id);closeDialog($("#courseLibraryDialog"));renderHome()}
function openCourseEditor(id=null){const src=id?state.courses.find(c=>c.id===id):null;state.editingCourseId=id;state.editorItems=src?clone(src.items):[{id:uid("item"),cue:"",question:"",answer:""}];$("#editorHeading").textContent=src?"문장 세트 편집":"문장 세트 만들기";$("#courseTitleInput").value=src?.title||"";$("#courseDescriptionInput").value=src?.description||"";$("#deleteCourseButton").classList.toggle("is-hidden",!src||src.builtIn);$("#editorError").classList.add("is-hidden");setEditorTab("cards");renderSentenceEditor();closeDialog($("#courseLibraryDialog"));openDialog($("#courseEditorDialog"))}
function renderSentenceEditor(){const list=$("#sentenceEditorList");list.innerHTML="";state.editorItems.forEach((item,index)=>{const card=document.createElement("section");card.className="sentence-editor-card";card.dataset.itemId=item.id;card.innerHTML=`<div class="sentence-card-head"><span class="sentence-number">${index+1}</span><strong>문장 ${index+1}</strong><button class="move-button move-up" type="button" ${index===0?"disabled":""}>↑</button><button class="move-button move-down" type="button" ${index===state.editorItems.length-1?"disabled":""}>↓</button><button class="remove-sentence" type="button">×</button></div><div class="sentence-fields"><label>Q · 전체 질문<textarea data-field="question" placeholder="시험에서 보게 될 전체 질문">${escapeHtml(item.question)}</textarea></label><label class="cue-field">CUE · 구분용 앞부분<textarea data-field="cue" placeholder="비워두면 질문 앞 5단어로 자동 생성">${escapeHtml(item.cue)}</textarea></label><label>A · 외울 답변<textarea data-field="answer" placeholder="정확히 외울 답변">${escapeHtml(item.answer)}</textarea></label></div>`;list.appendChild(card)});list.querySelectorAll("textarea[data-field]").forEach(t=>t.addEventListener("input",e=>updateEditorItem(e.currentTarget)));list.querySelectorAll(".move-up").forEach(b=>b.addEventListener("click",()=>moveEditorItem(b.closest(".sentence-editor-card").dataset.itemId,-1)));list.querySelectorAll(".move-down").forEach(b=>b.addEventListener("click",()=>moveEditorItem(b.closest(".sentence-editor-card").dataset.itemId,1)));list.querySelectorAll(".remove-sentence").forEach(b=>b.addEventListener("click",()=>removeEditorItem(b.closest(".sentence-editor-card").dataset.itemId)))}
function updateEditorItem(t){const card=t.closest(".sentence-editor-card"),item=state.editorItems.find(i=>i.id===card.dataset.itemId);if(item)item[t.dataset.field]=t.value}
function moveEditorItem(id,delta){const i=state.editorItems.findIndex(x=>x.id===id),n=i+delta;if(i<0||n<0||n>=state.editorItems.length)return;[state.editorItems[i],state.editorItems[n]]=[state.editorItems[n],state.editorItems[i]];renderSentenceEditor()}
function removeEditorItem(id){if(state.editorItems.length===1)return;state.editorItems=state.editorItems.filter(i=>i.id!==id);renderSentenceEditor()}
function addEditorItem(){state.editorItems.push({id:uid("item"),cue:"",question:"",answer:""});renderSentenceEditor();const cards=$$(".sentence-editor-card");cards[cards.length-1]?.scrollIntoView({behavior:"smooth",block:"center"})}
function setEditorTab(tab){$$(".editor-tab").forEach(b=>b.classList.toggle("is-active",b.dataset.editorTab===tab));$("#cardsEditorPanel").classList.toggle("is-hidden",tab!=="cards");$("#bulkEditorPanel").classList.toggle("is-hidden",tab!=="bulk");if(tab==="bulk")$("#bulkInput").value=serializeBulk(state.editorItems)}
function serializeBulk(items){return items.map(i=>`Q: ${i.question}\nCUE: ${i.cue||makeCue(i.question)}\nA: ${i.answer}`).join("\n---\n")}
function parseBulk(text){const blocks=text.split(/^\s*---\s*$/m).map(b=>b.trim()).filter(Boolean);if(!blocks.length)throw new Error("입력된 문장이 없음.");return blocks.map((block,index)=>{const data={question:"",cue:"",answer:""};let current=null;block.split(/\r?\n/).forEach(line=>{const m=line.match(/^\s*(Q|QUESTION|CUE|A|ANSWER)\s*:\s*(.*)$/i);if(m){const k=m[1].toUpperCase();current=k==="Q"||k==="QUESTION"?"question":k==="CUE"?"cue":"answer";data[current]=m[2].trim()}else if(current&&line.trim())data[current]+=`${data[current]?" ":""}${line.trim()}`});if(!data.question||!data.answer)throw new Error(`${index+1}번째 블록에 Q 또는 A가 비어 있음.`);if(!data.cue)data.cue=makeCue(data.question);return{id:uid("item"),...data}})}
function applyBulk(){try{state.editorItems=parseBulk($("#bulkInput").value);$("#editorError").classList.add("is-hidden");setEditorTab("cards");renderSentenceEditor()}catch(e){showEditorError(e.message)}}
function showEditorError(msg){$("#editorError").textContent=msg;$("#editorError").classList.remove("is-hidden")}
function saveCourse(){const title=$("#courseTitleInput").value.trim(),description=$("#courseDescriptionInput").value.trim(),items=state.editorItems.map(i=>({...i,question:i.question.trim(),cue:(i.cue||makeCue(i.question)).trim(),answer:i.answer.trim()}));if(!title)return showEditorError("세트 이름을 입력해야 함.");if(!items.length||items.some(i=>!i.question||!i.answer))return showEditorError("모든 문장에 Q와 A가 필요함.");const existing=state.courses.find(c=>c.id===state.editingCourseId);if(existing?.builtIn){const c={id:uid("course"),title:`${title} 복사본`,description,builtIn:false,items:items.map(i=>({...i,id:uid("item")}))};state.courses.push(c);state.activeCourseId=c.id}else if(existing){existing.title=title;existing.description=description;existing.items=items}else{const c={id:uid("course"),title,description,builtIn:false,items};state.courses.push(c);state.activeCourseId=c.id}localStorage.setItem(STORE.activeCourse,state.activeCourseId);persistCourses();ensureCourseProgress(state.activeCourseId);closeDialog($("#courseEditorDialog"));renderHome()}
function deleteCurrentCourse(){const c=state.courses.find(x=>x.id===state.editingCourseId);if(!c||c.builtIn)return;state.courses=state.courses.filter(x=>x.id!==c.id);delete state.progressByCourse[c.id];if(state.activeCourseId===c.id)state.activeCourseId=DEFAULT_COURSE.id;localStorage.setItem(STORE.activeCourse,state.activeCourseId);persistCourses();persistProgress();closeDialog($("#courseEditorDialog"));renderHome()}
function openOrderSettings(){$$('input[name="orderMode"]').forEach(i=>i.checked=i.value===state.settings.orderMode);$$('input[name="chunkSize"]').forEach(i=>i.checked=Number(i.value)===Number(state.settings.chunkSize));openDialog($("#orderDialog"))}
function saveOrderSettings(){state.settings={orderMode:$('input[name="orderMode"]:checked')?.value||"original",chunkSize:Number($('input[name="chunkSize"]:checked')?.value||3)};persistSettings();closeDialog($("#orderDialog"));renderHome()}
function openStats(){const p=getCourseProgress(),course=activeCourse();$("#statsCourseName").textContent=course.title;$("#statsXp").textContent=getGlobalStats().totalXp;$("#statsLessons").textContent=p.completedLessons.length;$("#statsWeak").textContent=Object.values(p.weak).filter(v=>Number(v)>0).length;const list=$("#sentenceStatsList");list.innerHTML="";course.items.forEach((item,index)=>{const attempts=Number(p.attempts[item.id]||0),mastered=Number(p.mastered[item.id]||0),weak=Number(p.weak[item.id]||0),row=document.createElement("div");row.className=`sentence-stat-row ${weak>0?"weak":mastered>0?"mastered":""}`;row.innerHTML=`<span class="status-dot">${index+1}</span><div><strong>${escapeHtml(item.cue||makeCue(item.question))}</strong><small>${attempts?`${attempts}회 시도`:"아직 학습 전"}</small></div><span class="sentence-stat-score">${weak>0?`약함 ${weak}`:mastered>0?`✓ ${mastered}`:"—"}</span>`;list.appendChild(row)});openDialog($("#statsDialog"))}
function handleNav(target){if(target==="sets")return openCourseLibrary();if(target==="practice")return quickPractice();if(target==="stats")return openStats();switchScreen($("#homeScreen"))}
function toggleFullQuestion(){const f=$("#fullQuestion"),hidden=f.classList.toggle("is-hidden");$("#fullQuestionToggle").textContent=hidden?"전체 질문 보기":"전체 질문 숨기기"}
function exitToHome(){closeDialog($("#exitDialog"));state.session=null;switchScreen($("#homeScreen"));renderHome()}
function bindEvents(){$("#openCourseLibrary").addEventListener("click",openCourseLibrary);$("#courseSwitcherMobile").addEventListener("click",openCourseLibrary);$("#courseMenuButton").addEventListener("click",openCourseLibrary);$("#openOrderSettings").addEventListener("click",openOrderSettings);$("#quickPractice").addEventListener("click",quickPractice);$("#railSettings").addEventListener("click",openOrderSettings);$$('[data-nav]').forEach(b=>b.addEventListener("click",()=>handleNav(b.dataset.nav)));$$('[data-close-dialog]').forEach(b=>b.addEventListener("click",()=>closeDialog(b.closest("dialog"))));$("#closeLessonSheet").addEventListener("click",()=>closeDialog($("#lessonSheet")));$("#startLessonFromSheet").addEventListener("click",startSelectedLesson);$("#createCourseButton").addEventListener("click",()=>openCourseEditor());$("#addSentenceButton").addEventListener("click",addEditorItem);$$(".editor-tab").forEach(b=>b.addEventListener("click",()=>setEditorTab(b.dataset.editorTab)));$("#applyBulkButton").addEventListener("click",applyBulk);$("#saveCourseButton").addEventListener("click",saveCourse);$("#cancelCourseEdit").addEventListener("click",()=>closeDialog($("#courseEditorDialog")));$("#deleteCourseButton").addEventListener("click",deleteCurrentCourse);$("#saveOrderSettings").addEventListener("click",saveOrderSettings);$("#answerInput").addEventListener("input",()=>{if(state.session&&!state.session.feedbackOpen)$("#checkButton").disabled=!$("#answerInput").value.trim()});$("#answerInput").addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key==="Enter"){e.preventDefault();checkAnswer()}});$("#checkButton").addEventListener("click",checkAnswer);$("#hintButton").addEventListener("click",revealHint);$("#revealButton").addEventListener("click",revealAnswer);$("#fullQuestionToggle").addEventListener("click",toggleFullQuestion);$("#exitLesson").addEventListener("click",()=>openDialog($("#exitDialog")));$("#keepLearning").addEventListener("click",()=>closeDialog($("#exitDialog")));$("#confirmExit").addEventListener("click",exitToHome);$("#retryMissed").addEventListener("click",retryMissed);$("#continuePath").addEventListener("click",continuePath);$("#backHome").addEventListener("click",()=>{switchScreen($("#homeScreen"));renderHome()})}
loadState();bindEvents();renderHome();
